(function(){"use strict";
var cart=new window.Cart(),discountId="none",category="all",search="";
var el={menu:document.getElementById("menu"),filters:document.getElementById("menu-filters"),search:document.getElementById("menu-search"),count:document.getElementById("menu-result-count"),body:document.getElementById("cart-body"),empty:document.getElementById("cart-empty"),discount:document.getElementById("discount"),subtotal:document.getElementById("subtotal"),discountRow:document.getElementById("discount-row"),discountAmount:document.getElementById("discount-amount"),total:document.getElementById("total"),itemCount:document.getElementById("item-count"),error:document.getElementById("error"),receipt:document.getElementById("receipt"),place:document.getElementById("place-order")};
function clearMessages(){el.error.hidden=true;el.error.textContent="";el.receipt.hidden=true;}
function renderMenu(){el.menu.innerHTML="";var items=window.MENU.filter(function(item){return(category==="all"||item.category===category)&&(item.name+" "+item.note+" "+item.category).toLowerCase().indexOf(search)!==-1;});el.count.textContent=items.length+(items.length===1?" lovely thing":" lovely things");items.forEach(function(item){var card=document.createElement("article");card.className="menu-item"+(item.inStock?"":" oos");var photo=document.createElement("div");photo.className="mi-photo";var img=document.createElement("img");img.src=item.image;img.alt=item.name+" from Campus Café";img.loading="lazy";img.onerror=function(){photo.classList.add("image-missing");img.remove();};photo.appendChild(img);var tag=document.createElement("span");tag.className="mi-tag";tag.textContent=item.inStock?item.tag:"BACK SOON";photo.appendChild(tag);var info=document.createElement("div");info.className="mi-info";var row=document.createElement("div");row.className="mi-title-row";var name=document.createElement("h3");name.className="mi-name";name.textContent=item.name;var price=document.createElement("span");price.className="mi-price";price.textContent=window.formatMoney(item.priceCents);row.appendChild(name);row.appendChild(price);var note=document.createElement("p");note.className="mi-note";note.textContent=item.note;var foot=document.createElement("div");foot.className="mi-footer";var meta=document.createElement("span");meta.className="mi-meta";meta.textContent=item.category==="drink"?"SOMETHING TO SIP":"FROM THE BAKERY";var add=document.createElement("button");add.type="button";add.className="add";add.innerHTML='<span aria-hidden="true">+</span> Add';add.setAttribute("aria-label",(item.inStock?"Add ":"Try ")+item.name+" to cart");add.addEventListener("click",function(){cart.add(item);clearMessages();});foot.appendChild(meta);foot.appendChild(add);info.appendChild(row);info.appendChild(note);info.appendChild(foot);card.appendChild(photo);card.appendChild(info);el.menu.appendChild(card);});if(!items.length){var none=document.createElement("p");none.className="no-results";none.textContent="Nothing here yet. Try another search or category.";el.menu.appendChild(none);}}
function renderFilters(){[{id:"all",label:"Everything"},{id:"drink",label:"Coffee & tea"},{id:"food",label:"Bakery"}].forEach(function(filter){var b=document.createElement("button");b.type="button";b.className="filter-pill"+(category===filter.id?" active":"");b.textContent=filter.label;b.setAttribute("aria-pressed",String(category===filter.id));b.addEventListener("click",function(){category=filter.id;renderFilters();renderMenu();});el.filters.appendChild(b);});}
function renderCart(s){el.body.innerHTML="";el.empty.hidden=!s.isEmpty;s.lines.forEach(function(line){var tr=document.createElement("tr"),n=document.createElement("td"),qtd=document.createElement("td"),q=document.createElement("input"),p=document.createElement("td"),d=document.createElement("td"),del=document.createElement("button");n.textContent=line.name;q.type="number";q.min="0";q.max="99";q.value=String(line.quantity);q.className="qty";q.id="qty-"+line.id;q.setAttribute("aria-label","Quantity for "+line.name);if(line.quantity<1||line.quantity>10)q.classList.add("bad");q.addEventListener("change",function(){var raw=q.value.trim();cart.setQuantity(line.id,raw===""?NaN:Number(raw));clearMessages();});qtd.appendChild(q);p.className="num";p.textContent=window.formatMoney(line.priceCents*line.quantity);del.type="button";del.className="remove";del.textContent="Remove";del.setAttribute("aria-label","Remove "+line.name);del.addEventListener("click",function(){cart.remove(line.id);clearMessages();});d.appendChild(del);[n,qtd,p,d].forEach(function(td){tr.appendChild(td);});el.body.appendChild(tr);});}
function renderTotals(s){var discount=window.getDiscount(discountId).apply(s.lines,s.subtotalCents);discount=Math.min(discount,s.subtotalCents);el.itemCount.textContent=s.itemCount+(s.itemCount===1?" item":" items");el.subtotal.textContent=window.formatMoney(s.subtotalCents);el.discountRow.hidden=discount===0;el.discountAmount.textContent="-"+window.formatMoney(discount);el.total.textContent=window.formatMoney(s.subtotalCents-discount);}
cart.subscribe(renderCart);cart.subscribe(renderTotals);
Object.keys(window.DISCOUNTS).forEach(function(id){var option=document.createElement("option");option.value=id;option.textContent=window.DISCOUNTS[id].label;el.discount.appendChild(option);});el.discount.value=discountId;el.discount.addEventListener("change",function(){discountId=el.discount.value;renderTotals(cart.getSnapshot());clearMessages();});el.search.addEventListener("input",function(){search=el.search.value.trim().toLowerCase();renderMenu();});
function showError(r){el.receipt.hidden=true;el.error.hidden=false;el.error.textContent="["+r.code+"] "+r.message;el.error.focus();}
function showReceipt(order){clearMessages();el.receipt.hidden=false;el.receipt.innerHTML="";var h=document.createElement("h3");h.textContent="Order "+order.id+" placed";el.receipt.appendChild(h);var list=document.createElement("ul");order.lines.forEach(function(line){var li=document.createElement("li");li.textContent=line.quantity+" x "+line.name+" — "+window.formatMoney(line.lineTotalCents);list.appendChild(li);});el.receipt.appendChild(list);[["Subtotal",window.formatMoney(order.subtotalCents)],[order.discountLabel,"-"+window.formatMoney(order.discountCents)],["Total",window.formatMoney(order.totalCents)]].forEach(function(r,i){var p=document.createElement("p");p.className="rc-row"+(i===2?" rc-total":"");var a=document.createElement("span"),b=document.createElement("span");a.textContent=r[0];b.textContent=r[1];p.appendChild(a);p.appendChild(b);el.receipt.appendChild(p);});}
el.place.addEventListener("click",function(){var r=window.placeOrder(cart,window.getDiscount(discountId));if(r.ok){showReceipt(r.order);cart.clear();return;}showError(r);if(r.code===window.ORDER_ERRORS.INVALID_QUANTITY){r.details.offenders.forEach(function(o){var q=document.getElementById("qty-"+o.id);if(q)q.classList.add("bad");});}});
renderFilters();renderMenu();cart.notify();
})();
